### PR TITLE
DOCS/NEW: Initial docs attempt for review + json_has_key / free_json.

### PR DESCRIPTION
**Pull request by jarmstrong**
Need clarification on how the following work and when they should be used:

* `static` (Assuming it is when a method needs access to a class but isn't passed any parameters?)
* `self`
* `method`

* Does the constructor attribute handle overloads or do we need to add a `unique` name?

### CODE REVIEW

**Comment by alexcu** [comment]
@jarmstrong Have you seen the doc guide? https://github.com/splashkit/splashkit-translator#splashkit-documentation-guidelines

If you're still unsure let me know. Might mean the docs need to be changed.

**Comment by jarmstrong** [comment]
@alexcu Thanks! I had forgotten to look here for docs.

**Comment by macite** [comment]
@alexcu Can you or @jakerenzella add something to the readme in splashkit about this?

**Comment by jakerenzella** [comment]
Done @macite 👍

**Pull request merged**
