### PR TITLE
Fix parser violations

### PR DESCRIPTION
**Pull request by alexcu**
Parser violations in the headerdoc was preventing translation. https://github.com/splashkit/splashkit-translator/pull/9 will list direct links to assist developers with rules and might be nice to add another CI check that makes sure the parser runs OK... @jarmstrong @macite thoughts?

### CODE REVIEW

**Comment by jarmstrong** [comment]
Sounds good, it might be better as a git hool though?

Also I need a special CMakeLists.txt in my root for CLion to work (tried to find another way) so thats why I ignore it directly in root, I think adding the ! makes the root one visible again. I think it can be fixed if you change the ! to be specific to the cmake folder

**Comment by alexcu** [comment]
If it were a git hook it means that each person would need to clone and regularly keep the clone updated, right?

Damn sorry I keep accidentally messing it up. The `cmake` folder shows as ignored but the file `CMakeLists.txt` isn't. Let me just revert it.

**Comment by alexcu** [comment]
I'll try adding this to OS X's travis run. The validation needs headerdoc2html which will come with the Xcode image we use in travis. Only needs to run once for one OS anyway.

**Comment by jarmstrong** [comment]
Could the git hook ensure that the clone is up to date before running? I think it makes sense to get quick feedback before committing

**Comment by alexcu** [comment]
The translator (at the moment) takes about a minute to validate (due to lots of warnings with our documentation)... would definitely get in the way during commit.

Plus to get HeaderDoc on Linux can be a bit tricky (it's a dependency)...

**Comment by jarmstrong** [comment]
Ahhh ok, maybe in the future when we fix more up then / can get it sorted x-platform? I like the idea of instant feedback :D

**Comment by jarmstrong** [comment]
CI for now would be cool.

**Comment by alexcu** [comment]
Agreed. There is definitely a way to get HeaderDoc running cross-platform, but I haven't looked at it too much. Let's aim to make the OS X CI work for us for now.

**Comment by alexcu** [comment]
Deprecate for https://github.com/splashkit/splashkit/pull/51

**Pull request closed without merging**
